[package]
name = "reader_core"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
thiserror = "2.0"
zxing-cpp = { version = "0.5.0", features = ["bundled"] }
